## Numpy arrays v Python lists


Create a numpy array of 10000 random numbers.

In [1]:
X = [1, 2, 3, 4, 5]

In [8]:
x = 42

In [ ]:
sum(X)

In [3]:
mean(X)

NameError: name 'mean' is not defined

In [4]:
sd(X)

NameError: name 'sd' is not defined

In [5]:
import numpy 

In [6]:
import numpy as np

In [10]:
x = np.random.rand(10000)

In [12]:
x_list = list(x)

In [13]:
type(x)

numpy.ndarray

In [14]:
type(x_list)

list

In [15]:
x.sum()

5005.2596436225085

In [16]:
np.sum(x)

5005.2596436225085

In [17]:
sum(x_list)

5005.259643622486

In [18]:
%timeit x.sum()

3.7 µs ± 107 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [19]:
%timeit sum(x_list)

805 µs ± 27 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [20]:
807/3.7

218.1081081081081

In [22]:
(5 * 200)/60

16.666666666666668

In [23]:
(x > .5).sum()

4992

## Operations on numpy arrays

In [24]:
x = numpy.random.rand(10000)
y = numpy.random.rand(10000)

In [27]:
z = x + y
x - y
x * y
x / y

array([0.48938154, 1.70488619, 0.94183998, ..., 1.64535589, 2.29581001,
       0.5280383 ])

In [28]:
x + 2

array([2.38824255, 2.72582769, 2.63445064, ..., 2.79602859, 2.72264625,
       2.51824152])

In [29]:
np.log(x)

array([-0.946125  , -0.32044264, -0.45499579, ..., -0.22812017,
       -0.32483545, -0.6573139 ])

## Indexing and slicing

In [31]:
x[:10]

array([0.38824255, 0.72582769, 0.63445064, 0.6256456 , 0.9125765 ,
       0.0957928 , 0.7226939 , 0.07630838, 0.75086434, 0.1990251 ])

In [33]:
x[0:2]

array([0.38824255, 0.72582769])

In [34]:
x[:2]

array([0.38824255, 0.72582769])

In [35]:
x[:10]

array([0.38824255, 0.72582769, 0.63445064, 0.6256456 , 0.9125765 ,
       0.0957928 , 0.7226939 , 0.07630838, 0.75086434, 0.1990251 ])

In [36]:
x[0:10]

array([0.38824255, 0.72582769, 0.63445064, 0.6256456 , 0.9125765 ,
       0.0957928 , 0.7226939 , 0.07630838, 0.75086434, 0.1990251 ])

In [37]:
x[0:10:2]

array([0.38824255, 0.63445064, 0.9125765 , 0.7226939 , 0.75086434])

In [38]:
x[:10:2]

array([0.38824255, 0.63445064, 0.9125765 , 0.7226939 , 0.75086434])

In [39]:
x[:10]

array([0.38824255, 0.72582769, 0.63445064, 0.6256456 , 0.9125765 ,
       0.0957928 , 0.7226939 , 0.07630838, 0.75086434, 0.1990251 ])

In [40]:
x[:10:1]

array([0.38824255, 0.72582769, 0.63445064, 0.6256456 , 0.9125765 ,
       0.0957928 , 0.7226939 , 0.07630838, 0.75086434, 0.1990251 ])

In [41]:
x[10:]

array([0.28753341, 0.49967163, 0.76608519, ..., 0.79602859, 0.72264625,
       0.51824152])

In [42]:
x[10::2]

array([0.28753341, 0.76608519, 0.79694755, ..., 0.28689421, 0.59793855,
       0.72264625])

In [45]:
x[::100].sum()

49.31304377120393

In [46]:
x[1200]

0.18238713469155454

In [48]:
x[[10,110]]

array([0.28753341, 0.69572191])

## Create numpy arrays

In [49]:
x = np.random.rand(3, 5)

In [50]:
x

array([[0.02025212, 0.013981  , 0.9019091 , 0.94206665, 0.82632327],
       [0.96364759, 0.01531872, 0.47047406, 0.76368463, 0.94045645],
       [0.00101273, 0.77650934, 0.0210274 , 0.04760398, 0.4822329 ]])

In [51]:
x.shape

(3, 5)

In [52]:
x.size

15

In [53]:
x = np.random.rand(3, 5, 2)

In [54]:
x.shape

(3, 5, 2)

In [55]:
x

array([[[0.80500384, 0.81531513],
        [0.3446153 , 0.09683275],
        [0.9838458 , 0.14998268],
        [0.48936948, 0.79382951],
        [0.35874567, 0.52763154]],

       [[0.21534834, 0.04581728],
        [0.08574044, 0.45628496],
        [0.51019409, 0.86603596],
        [0.34391949, 0.9186883 ],
        [0.34228328, 0.63141904]],

       [[0.30903425, 0.37191207],
        [0.29637624, 0.52358613],
        [0.75300186, 0.54359662],
        [0.59372962, 0.75033985],
        [0.48763642, 0.54843892]]])

In [56]:
x = np.random.rand(1000)

In [57]:
x.shape

(1000,)

In [58]:
x = 42

In [59]:
type(x)

int

In [61]:
(x,)

(42,)

In [65]:
np.empty((10, 2))

array([[1.13553475e-313, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 5.30276956e+180],
       [1.57076922e-076, 4.57222315e-071],
       [5.06557763e-086, 3.35910089e-143],
       [6.01433264e+175, 6.93885958e+218],
       [5.56218858e+180, 3.94356143e+180],
       [2.48357131e+184, 6.07727855e-067],
       [8.23039567e-071, 1.34972584e+161],
       [5.19715252e-144, 1.50008929e+248]])

In [68]:
np.full((10, 2), 42)

array([[42, 42],
       [42, 42],
       [42, 42],
       [42, 42],
       [42, 42],
       [42, 42],
       [42, 42],
       [42, 42],
       [42, 42],
       [42, 42]])

In [69]:
np.ones((10, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [70]:
np.zeros((10, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [71]:
np.linspace(0, 1, 50)

array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
       0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
       0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
       0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
       0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
       0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
       0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
       0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
       0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
       0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ])

In [72]:
x = [1, 2, 3]

In [74]:
x = np.array([1, 2, 3])

In [75]:
x

array([1, 2, 3])

## Numpy data types

In [76]:
x = np.array([1, 2, 3])

In [77]:
x.dtype

dtype('int64')

In [78]:
type(x)

numpy.ndarray

In [79]:
type([1, 2, 3])

list

In [80]:
x = np.array([1, 2, 3], dtype = np.int8)

In [81]:
x

array([1, 2, 3], dtype=int8)

In [82]:
x.dtype

dtype('int8')

In [83]:
x = np.random.rand(10)

In [84]:
x

array([0.29413519, 0.55022663, 0.86585997, 0.30770853, 0.76781319,
       0.68123873, 0.73149249, 0.93311124, 0.21801967, 0.71917182])

In [85]:
x.dtype

dtype('float64')

In [86]:
%rep 83

In [88]:
x = np.array([1, 2, 3], dtype = np.float128)

In [89]:
x.dtype

dtype('float128')

In [90]:
x

array([1., 2., 3.], dtype=float128)

In [94]:
x = np.array([1, 0, 1, 0, 1], dtype = np.bool)

In [95]:
x

array([ True, False,  True, False,  True])

In [93]:
x.dtype

dtype('int64')

In [96]:
%rep 94

In [102]:
x = np.array([1, 0, 1, 0, 1])

In [98]:
x.dtype = np.bool

In [103]:
x

array([1, 0, 1, 0, 1])

In [104]:
x

array([1, 0, 1, 0, 1])

## Reshaping arrays

In [107]:
x = np.random.rand(10, 5)

In [108]:
x.shape

(10, 5)

In [109]:
x.reshape((25, 2))

array([[0.34194824, 0.65604685],
       [0.3552232 , 0.98047157],
       [0.06744912, 0.40580879],
       [0.79652155, 0.88452743],
       [0.16020086, 0.71235384],
       [0.12161899, 0.51492329],
       [0.24479173, 0.13210059],
       [0.31322015, 0.59222997],
       [0.88448109, 0.35601279],
       [0.01305915, 0.00524033],
       [0.58487192, 0.73637899],
       [0.6493385 , 0.30396422],
       [0.05997882, 0.40364687],
       [0.81172281, 0.67501858],
       [0.49454516, 0.79851958],
       [0.92610625, 0.104666  ],
       [0.89273077, 0.3003011 ],
       [0.05197847, 0.09239899],
       [0.84119636, 0.56410686],
       [0.78566087, 0.06903019],
       [0.244288  , 0.83493001],
       [0.80551993, 0.64882826],
       [0.37007163, 0.45381114],
       [0.88031383, 0.79158669],
       [0.9671576 , 0.99862126]])

In [110]:
x

array([[0.34194824, 0.65604685, 0.3552232 , 0.98047157, 0.06744912],
       [0.40580879, 0.79652155, 0.88452743, 0.16020086, 0.71235384],
       [0.12161899, 0.51492329, 0.24479173, 0.13210059, 0.31322015],
       [0.59222997, 0.88448109, 0.35601279, 0.01305915, 0.00524033],
       [0.58487192, 0.73637899, 0.6493385 , 0.30396422, 0.05997882],
       [0.40364687, 0.81172281, 0.67501858, 0.49454516, 0.79851958],
       [0.92610625, 0.104666  , 0.89273077, 0.3003011 , 0.05197847],
       [0.09239899, 0.84119636, 0.56410686, 0.78566087, 0.06903019],
       [0.244288  , 0.83493001, 0.80551993, 0.64882826, 0.37007163],
       [0.45381114, 0.88031383, 0.79158669, 0.9671576 , 0.99862126]])

In [111]:
x.reshape((5, 2, 5))

array([[[0.34194824, 0.65604685, 0.3552232 , 0.98047157, 0.06744912],
        [0.40580879, 0.79652155, 0.88452743, 0.16020086, 0.71235384]],

       [[0.12161899, 0.51492329, 0.24479173, 0.13210059, 0.31322015],
        [0.59222997, 0.88448109, 0.35601279, 0.01305915, 0.00524033]],

       [[0.58487192, 0.73637899, 0.6493385 , 0.30396422, 0.05997882],
        [0.40364687, 0.81172281, 0.67501858, 0.49454516, 0.79851958]],

       [[0.92610625, 0.104666  , 0.89273077, 0.3003011 , 0.05197847],
        [0.09239899, 0.84119636, 0.56410686, 0.78566087, 0.06903019]],

       [[0.244288  , 0.83493001, 0.80551993, 0.64882826, 0.37007163],
        [0.45381114, 0.88031383, 0.79158669, 0.9671576 , 0.99862126]]])

In [113]:
x.T

array([[0.34194824, 0.40580879, 0.12161899, 0.59222997, 0.58487192,
        0.40364687, 0.92610625, 0.09239899, 0.244288  , 0.45381114],
       [0.65604685, 0.79652155, 0.51492329, 0.88448109, 0.73637899,
        0.81172281, 0.104666  , 0.84119636, 0.83493001, 0.88031383],
       [0.3552232 , 0.88452743, 0.24479173, 0.35601279, 0.6493385 ,
        0.67501858, 0.89273077, 0.56410686, 0.80551993, 0.79158669],
       [0.98047157, 0.16020086, 0.13210059, 0.01305915, 0.30396422,
        0.49454516, 0.3003011 , 0.78566087, 0.64882826, 0.9671576 ],
       [0.06744912, 0.71235384, 0.31322015, 0.00524033, 0.05997882,
        0.79851958, 0.05197847, 0.06903019, 0.37007163, 0.99862126]])

In [114]:
x.shape

(10, 5)

In [115]:
x.T.shape

(5, 10)

In [118]:
y = x.reshape((5, 5, 2))

In [121]:
y.flatten()

array([0.34194824, 0.65604685, 0.3552232 , 0.98047157, 0.06744912,
       0.40580879, 0.79652155, 0.88452743, 0.16020086, 0.71235384,
       0.12161899, 0.51492329, 0.24479173, 0.13210059, 0.31322015,
       0.59222997, 0.88448109, 0.35601279, 0.01305915, 0.00524033,
       0.58487192, 0.73637899, 0.6493385 , 0.30396422, 0.05997882,
       0.40364687, 0.81172281, 0.67501858, 0.49454516, 0.79851958,
       0.92610625, 0.104666  , 0.89273077, 0.3003011 , 0.05197847,
       0.09239899, 0.84119636, 0.56410686, 0.78566087, 0.06903019,
       0.244288  , 0.83493001, 0.80551993, 0.64882826, 0.37007163,
       0.45381114, 0.88031383, 0.79158669, 0.9671576 , 0.99862126])

In [123]:
y.flatten().shape

(50,)

## More on operations

In [124]:
y = np.random.rand(10)


In [126]:
y

array([0.8987414 , 0.28153093, 0.79133586, 0.43545318, 0.90244206,
       0.5912478 , 0.18537188, 0.99855869, 0.54956445, 0.98294782])

In [127]:
y.sort()

In [128]:
y

array([0.18537188, 0.28153093, 0.43545318, 0.54956445, 0.5912478 ,
       0.79133586, 0.8987414 , 0.90244206, 0.98294782, 0.99855869])

In [129]:
?y.sort


In [130]:
y

array([0.18537188, 0.28153093, 0.43545318, 0.54956445, 0.5912478 ,
       0.79133586, 0.8987414 , 0.90244206, 0.98294782, 0.99855869])

In [131]:
y = np.random.rand(10)

In [132]:

y

array([0.85464426, 0.56454074, 0.64574772, 0.97600953, 0.70911277,
       0.69029939, 0.12703812, 0.80806447, 0.39132706, 0.43888236])

In [133]:
y.sort()

In [136]:
np.flipud(y)

array([0.97600953, 0.85464426, 0.80806447, 0.70911277, 0.69029939,
       0.64574772, 0.56454074, 0.43888236, 0.39132706, 0.12703812])

In [140]:
x = np.random.rand(10, 5)

In [141]:
x

array([[0.64770735, 0.17915517, 0.46270874, 0.30452717, 0.95829241],
       [0.74897924, 0.9346415 , 0.94991172, 0.84383522, 0.87292258],
       [0.5692569 , 0.84442502, 0.85696244, 0.31155415, 0.50012774],
       [0.97123707, 0.85159962, 0.44766406, 0.8723886 , 0.23067119],
       [0.75446097, 0.84439945, 0.38066791, 0.64580003, 0.89867403],
       [0.81342548, 0.4954956 , 0.82984751, 0.32990021, 0.43192302],
       [0.7083111 , 0.54272873, 0.48841959, 0.93899834, 0.99932635],
       [0.88989807, 0.47626405, 0.26031139, 0.89202271, 0.43095132],
       [0.14847266, 0.84742142, 0.98877215, 0.59015038, 0.56825083],
       [0.67733417, 0.42589251, 0.65401028, 0.25492032, 0.9248589 ]])

In [142]:
x

array([[0.64770735, 0.17915517, 0.46270874, 0.30452717, 0.95829241],
       [0.74897924, 0.9346415 , 0.94991172, 0.84383522, 0.87292258],
       [0.5692569 , 0.84442502, 0.85696244, 0.31155415, 0.50012774],
       [0.97123707, 0.85159962, 0.44766406, 0.8723886 , 0.23067119],
       [0.75446097, 0.84439945, 0.38066791, 0.64580003, 0.89867403],
       [0.81342548, 0.4954956 , 0.82984751, 0.32990021, 0.43192302],
       [0.7083111 , 0.54272873, 0.48841959, 0.93899834, 0.99932635],
       [0.88989807, 0.47626405, 0.26031139, 0.89202271, 0.43095132],
       [0.14847266, 0.84742142, 0.98877215, 0.59015038, 0.56825083],
       [0.67733417, 0.42589251, 0.65401028, 0.25492032, 0.9248589 ]])

In [143]:
x.sum()

32.49047739154767

In [144]:
x.sum(axis = 0)

array([6.92908301, 6.44202308, 6.31927579, 5.98409714, 6.81599837])

In [145]:
x.sum(axis = 1)

array([2.55239084, 4.35029026, 3.08232625, 3.37356055, 3.52400239,
       2.90059183, 3.67778412, 2.94944754, 3.14306744, 2.93701618])

In [146]:
x.mean()

0.6498095478309535

In [147]:
x.mean(axis = 0)

array([0.6929083 , 0.64420231, 0.63192758, 0.59840971, 0.68159984])

In [148]:
x.mean(axis = 1)

array([0.51047817, 0.87005805, 0.61646525, 0.67471211, 0.70480048,
       0.58011837, 0.73555682, 0.58988951, 0.62861349, 0.58740324])

In [150]:
x.cumsum(axis = 0)

array([[0.64770735, 0.17915517, 0.46270874, 0.30452717, 0.95829241],
       [1.39668659, 1.11379667, 1.41262046, 1.14836239, 1.83121499],
       [1.96594349, 1.95822169, 2.2695829 , 1.45991654, 2.33134273],
       [2.93718056, 2.80982131, 2.71724696, 2.33230514, 2.56201392],
       [3.69164153, 3.65422076, 3.09791487, 2.97810517, 3.46068795],
       [4.50506701, 4.14971637, 3.92776238, 3.30800538, 3.89261098],
       [5.21337811, 4.6924451 , 4.41618197, 4.24700373, 4.89193732],
       [6.10327618, 5.16870915, 4.67649336, 5.13902644, 5.32288864],
       [6.25174884, 6.01613057, 5.66526551, 5.72917682, 5.89113947],
       [6.92908301, 6.44202308, 6.31927579, 5.98409714, 6.81599837]])

In [151]:
x

array([[0.64770735, 0.17915517, 0.46270874, 0.30452717, 0.95829241],
       [0.74897924, 0.9346415 , 0.94991172, 0.84383522, 0.87292258],
       [0.5692569 , 0.84442502, 0.85696244, 0.31155415, 0.50012774],
       [0.97123707, 0.85159962, 0.44766406, 0.8723886 , 0.23067119],
       [0.75446097, 0.84439945, 0.38066791, 0.64580003, 0.89867403],
       [0.81342548, 0.4954956 , 0.82984751, 0.32990021, 0.43192302],
       [0.7083111 , 0.54272873, 0.48841959, 0.93899834, 0.99932635],
       [0.88989807, 0.47626405, 0.26031139, 0.89202271, 0.43095132],
       [0.14847266, 0.84742142, 0.98877215, 0.59015038, 0.56825083],
       [0.67733417, 0.42589251, 0.65401028, 0.25492032, 0.9248589 ]])

In [152]:
x.cumsum(axis = 1)

array([[0.64770735, 0.82686253, 1.28957126, 1.59409843, 2.55239084],
       [0.74897924, 1.68362073, 2.63353246, 3.47736768, 4.35029026],
       [0.5692569 , 1.41368192, 2.27064436, 2.58219851, 3.08232625],
       [0.97123707, 1.82283669, 2.27050075, 3.14288935, 3.37356055],
       [0.75446097, 1.59886042, 1.97952833, 2.62532836, 3.52400239],
       [0.81342548, 1.30892108, 2.13876859, 2.4686688 , 2.90059183],
       [0.7083111 , 1.25103983, 1.73945943, 2.67845777, 3.67778412],
       [0.88989807, 1.36616212, 1.62647351, 2.51849623, 2.94944754],
       [0.14847266, 0.99589408, 1.98466623, 2.57481661, 3.14306744],
       [0.67733417, 1.10322668, 1.75723697, 2.01215728, 2.93701618]])

In [153]:
np.mean(x, axis = 0)

array([0.6929083 , 0.64420231, 0.63192758, 0.59840971, 0.68159984])

In [154]:
np.mean(x)

0.6498095478309535

In [157]:
x.max()

0.9993263494618303

In [156]:
x

array([[0.64770735, 0.17915517, 0.46270874, 0.30452717, 0.95829241],
       [0.74897924, 0.9346415 , 0.94991172, 0.84383522, 0.87292258],
       [0.5692569 , 0.84442502, 0.85696244, 0.31155415, 0.50012774],
       [0.97123707, 0.85159962, 0.44766406, 0.8723886 , 0.23067119],
       [0.75446097, 0.84439945, 0.38066791, 0.64580003, 0.89867403],
       [0.81342548, 0.4954956 , 0.82984751, 0.32990021, 0.43192302],
       [0.7083111 , 0.54272873, 0.48841959, 0.93899834, 0.99932635],
       [0.88989807, 0.47626405, 0.26031139, 0.89202271, 0.43095132],
       [0.14847266, 0.84742142, 0.98877215, 0.59015038, 0.56825083],
       [0.67733417, 0.42589251, 0.65401028, 0.25492032, 0.9248589 ]])

In [159]:
x.max(axis = 0)

array([0.97123707, 0.9346415 , 0.98877215, 0.93899834, 0.99932635])

In [160]:
x.max(axis = 1)

array([0.95829241, 0.94991172, 0.85696244, 0.97123707, 0.89867403,
       0.82984751, 0.99932635, 0.89202271, 0.98877215, 0.9248589 ])

In [162]:
x.sort(axis = 0)

In [163]:
x

array([[0.14847266, 0.17915517, 0.26031139, 0.25492032, 0.23067119],
       [0.5692569 , 0.42589251, 0.38066791, 0.30452717, 0.43095132],
       [0.64770735, 0.47626405, 0.44766406, 0.31155415, 0.43192302],
       [0.67733417, 0.4954956 , 0.46270874, 0.32990021, 0.50012774],
       [0.7083111 , 0.54272873, 0.48841959, 0.59015038, 0.56825083],
       [0.74897924, 0.84439945, 0.65401028, 0.64580003, 0.87292258],
       [0.75446097, 0.84442502, 0.82984751, 0.84383522, 0.89867403],
       [0.81342548, 0.84742142, 0.85696244, 0.8723886 , 0.9248589 ],
       [0.88989807, 0.85159962, 0.94991172, 0.89202271, 0.95829241],
       [0.97123707, 0.9346415 , 0.98877215, 0.93899834, 0.99932635]])

In [164]:
np.flipud(x)

array([[0.97123707, 0.9346415 , 0.98877215, 0.93899834, 0.99932635],
       [0.88989807, 0.85159962, 0.94991172, 0.89202271, 0.95829241],
       [0.81342548, 0.84742142, 0.85696244, 0.8723886 , 0.9248589 ],
       [0.75446097, 0.84442502, 0.82984751, 0.84383522, 0.89867403],
       [0.74897924, 0.84439945, 0.65401028, 0.64580003, 0.87292258],
       [0.7083111 , 0.54272873, 0.48841959, 0.59015038, 0.56825083],
       [0.67733417, 0.4954956 , 0.46270874, 0.32990021, 0.50012774],
       [0.64770735, 0.47626405, 0.44766406, 0.31155415, 0.43192302],
       [0.5692569 , 0.42589251, 0.38066791, 0.30452717, 0.43095132],
       [0.14847266, 0.17915517, 0.26031139, 0.25492032, 0.23067119]])

## stacking numpy arrays


In [165]:
x = np.random.rand(5, 3)
y = np.random.rand(3, 3)

In [166]:
(x,y)

(array([[0.55915584, 0.61180559, 0.62311647],
        [0.14949944, 0.24482692, 0.04610913],
        [0.09572467, 0.18543116, 0.07187317],
        [0.77967028, 0.32853229, 0.46774517],
        [0.98858493, 0.18080158, 0.22727487]]),
 array([[0.43173563, 0.0662458 , 0.82242628],
        [0.05104012, 0.88640294, 0.59331608],
        [0.78025656, 0.74894085, 0.96716906]]))

In [167]:
np.vstack((x, y))

array([[0.55915584, 0.61180559, 0.62311647],
       [0.14949944, 0.24482692, 0.04610913],
       [0.09572467, 0.18543116, 0.07187317],
       [0.77967028, 0.32853229, 0.46774517],
       [0.98858493, 0.18080158, 0.22727487],
       [0.43173563, 0.0662458 , 0.82242628],
       [0.05104012, 0.88640294, 0.59331608],
       [0.78025656, 0.74894085, 0.96716906]])

In [168]:
np.r_[x, y]

array([[0.55915584, 0.61180559, 0.62311647],
       [0.14949944, 0.24482692, 0.04610913],
       [0.09572467, 0.18543116, 0.07187317],
       [0.77967028, 0.32853229, 0.46774517],
       [0.98858493, 0.18080158, 0.22727487],
       [0.43173563, 0.0662458 , 0.82242628],
       [0.05104012, 0.88640294, 0.59331608],
       [0.78025656, 0.74894085, 0.96716906]])

In [169]:
z = np.random.rand(5, 5)

In [170]:
x

array([[0.55915584, 0.61180559, 0.62311647],
       [0.14949944, 0.24482692, 0.04610913],
       [0.09572467, 0.18543116, 0.07187317],
       [0.77967028, 0.32853229, 0.46774517],
       [0.98858493, 0.18080158, 0.22727487]])

In [171]:
z

array([[0.79697546, 0.82804502, 0.09136732, 0.17139521, 0.7608476 ],
       [0.29950282, 0.10015286, 0.81248243, 0.29181409, 0.00156742],
       [0.23565508, 0.28059703, 0.34269637, 0.33921985, 0.00981113],
       [0.64020228, 0.71570378, 0.07710458, 0.33569678, 0.85396572],
       [0.22862999, 0.54492867, 0.1862676 , 0.85855045, 0.84381334]])

In [175]:
np.hstack((x, z))

array([[0.55915584, 0.61180559, 0.62311647, 0.79697546, 0.82804502,
        0.09136732, 0.17139521, 0.7608476 ],
       [0.14949944, 0.24482692, 0.04610913, 0.29950282, 0.10015286,
        0.81248243, 0.29181409, 0.00156742],
       [0.09572467, 0.18543116, 0.07187317, 0.23565508, 0.28059703,
        0.34269637, 0.33921985, 0.00981113],
       [0.77967028, 0.32853229, 0.46774517, 0.64020228, 0.71570378,
        0.07710458, 0.33569678, 0.85396572],
       [0.98858493, 0.18080158, 0.22727487, 0.22862999, 0.54492867,
        0.1862676 , 0.85855045, 0.84381334]])

In [176]:
np.c_[x, z]

array([[0.55915584, 0.61180559, 0.62311647, 0.79697546, 0.82804502,
        0.09136732, 0.17139521, 0.7608476 ],
       [0.14949944, 0.24482692, 0.04610913, 0.29950282, 0.10015286,
        0.81248243, 0.29181409, 0.00156742],
       [0.09572467, 0.18543116, 0.07187317, 0.23565508, 0.28059703,
        0.34269637, 0.33921985, 0.00981113],
       [0.77967028, 0.32853229, 0.46774517, 0.64020228, 0.71570378,
        0.07710458, 0.33569678, 0.85396572],
       [0.98858493, 0.18080158, 0.22727487, 0.22862999, 0.54492867,
        0.1862676 , 0.85855045, 0.84381334]])

## broadcasting

In [177]:
x = np.random.rand(10)

In [178]:
x

array([0.28793758, 0.26098614, 0.00679845, 0.44622336, 0.34116883,
       0.27983802, 0.45335958, 0.66398022, 0.8199232 , 0.39206078])

In [179]:
x + 2.0 

array([2.28793758, 2.26098614, 2.00679845, 2.44622336, 2.34116883,
       2.27983802, 2.45335958, 2.66398022, 2.8199232 , 2.39206078])

In [180]:
x

array([0.28793758, 0.26098614, 0.00679845, 0.44622336, 0.34116883,
       0.27983802, 0.45335958, 0.66398022, 0.8199232 , 0.39206078])

In [181]:
y = np.random.rand(5, 10)

In [182]:
x

array([0.28793758, 0.26098614, 0.00679845, 0.44622336, 0.34116883,
       0.27983802, 0.45335958, 0.66398022, 0.8199232 , 0.39206078])

In [183]:
y

array([[0.06736594, 0.36175163, 0.13412776, 0.88679587, 0.20006939,
        0.20195201, 0.83276368, 0.56359361, 0.36638931, 0.58173914],
       [0.26612403, 0.70844552, 0.13998838, 0.14011247, 0.96776996,
        0.68024852, 0.22066346, 0.03789045, 0.78677884, 0.73375821],
       [0.69810188, 0.24379762, 0.20034467, 0.85002891, 0.95488756,
        0.45555232, 0.4255064 , 0.21368729, 0.37843189, 0.8219036 ],
       [0.98185518, 0.16045339, 0.04493646, 0.07256669, 0.39105478,
        0.99409981, 0.80690568, 0.67448951, 0.97223286, 0.75544534],
       [0.17586299, 0.67313832, 0.4991738 , 0.21200892, 0.78149286,
        0.20614165, 0.99376441, 0.43767879, 0.72573025, 0.12554611]])

In [184]:
x + y 

array([[0.35530352, 0.62273776, 0.14092621, 1.33301923, 0.54123821,
        0.48179002, 1.28612326, 1.22757384, 1.18631251, 0.97379992],
       [0.55406161, 0.96943166, 0.14678683, 0.58633583, 1.30893879,
        0.96008654, 0.67402304, 0.70187068, 1.60670204, 1.12581899],
       [0.98603946, 0.50478376, 0.20714312, 1.29625227, 1.29605639,
        0.73539034, 0.87886598, 0.87766751, 1.19835509, 1.21396438],
       [1.26979276, 0.42143953, 0.05173491, 0.51879005, 0.73222361,
        1.27393782, 1.26026526, 1.33846974, 1.79215606, 1.14750612],
       [0.46380057, 0.93412446, 0.50597225, 0.65823228, 1.12266168,
        0.48597967, 1.447124  , 1.10165901, 1.54565345, 0.51760689]])

In [185]:
x.shape

(10,)

In [186]:
y.shape

(5, 10)

In [187]:
x = np.random.rand(3)

In [188]:
x

array([0.64520355, 0.85208518, 0.7288368 ])

In [189]:
x.shape

(3,)

In [191]:
y = x.reshape((3, 1))

In [192]:
y.shape

(3, 1)

In [193]:
x.shape

(3,)

In [194]:
x


array([0.64520355, 0.85208518, 0.7288368 ])

In [195]:
y

array([[0.64520355],
       [0.85208518],
       [0.7288368 ]])

In [196]:
x + y

array([[1.29040711, 1.49728873, 1.37404035],
       [1.49728873, 1.70417036, 1.58092198],
       [1.37404035, 1.58092198, 1.4576736 ]])

In [197]:
x

array([0.64520355, 0.85208518, 0.7288368 ])

## Linear algebra, matrix operations

In [200]:
x = np.random.rand(3)
y = np.random.rand(3)

In [201]:
x

array([0.81037607, 0.88569432, 0.85150288])

In [202]:
y

array([0.46800704, 0.23049331, 0.08437641])

In [204]:
(x * y).sum()

0.6552550778131954

In [205]:
z = x * y
z.sum()

0.6552550778131954

In [206]:
np.inner(x, y)

0.6552550778131954

In [207]:
np.dot(x, y)

0.6552550778131954

In [208]:
x = np.random.rand(5, 3)
y = np.random.rand(3, 2)

In [209]:
x @ y 

array([[1.08657362, 1.22586795],
       [1.22408866, 1.24622943],
       [1.30217286, 1.13100307],
       [1.32810147, 1.47638815],
       [1.05204946, 1.09501404]])

In [210]:
x * y

ValueError: operands could not be broadcast together with shapes (5,3) (3,2) 

In [211]:
x @ y

array([[1.08657362, 1.22586795],
       [1.22408866, 1.24622943],
       [1.30217286, 1.13100307],
       [1.32810147, 1.47638815],
       [1.05204946, 1.09501404]])

In [213]:
np.dot(x, y)

array([[1.08657362, 1.22586795],
       [1.22408866, 1.24622943],
       [1.30217286, 1.13100307],
       [1.32810147, 1.47638815],
       [1.05204946, 1.09501404]])

In [214]:
x

array([[0.63776322, 0.24764868, 0.5250217 ],
       [0.47135271, 0.53843555, 0.5389729 ],
       [0.21788733, 0.90260515, 0.4546989 ],
       [0.39568005, 0.55536339, 0.83331733],
       [0.69014715, 0.26902112, 0.33205723]])

In [215]:
y

array([[0.89582882, 0.90323027],
       [0.96021451, 0.53975265],
       [0.52845643, 0.98310579]])

In [216]:
np.inner(x, y.T)

array([[1.08657362, 1.22586795],
       [1.22408866, 1.24622943],
       [1.30217286, 1.13100307],
       [1.32810147, 1.47638815],
       [1.05204946, 1.09501404]])

In [217]:
x, y.T

(array([[0.63776322, 0.24764868, 0.5250217 ],
        [0.47135271, 0.53843555, 0.5389729 ],
        [0.21788733, 0.90260515, 0.4546989 ],
        [0.39568005, 0.55536339, 0.83331733],
        [0.69014715, 0.26902112, 0.33205723]]),
 array([[0.89582882, 0.96021451, 0.52845643],
        [0.90323027, 0.53975265, 0.98310579]]))

In [219]:
?np.dot