In [1]:
import numpy as np

In [2]:
n = 10000
d = 3
k = 5

In [3]:
X = np.random.rand(n, d)

In [4]:
X.shape

(10000, 3)

In [5]:
X

array([[0.65315625, 0.40880671, 0.7244756 ],
       [0.87756297, 0.85481215, 0.38634009],
       [0.75709815, 0.6275608 , 0.26147569],
       ...,
       [0.43652731, 0.88373801, 0.62834258],
       [0.57773907, 0.68170715, 0.06264371],
       [0.50502735, 0.24627424, 0.46256502]])

In [6]:
centroids = np.random.rand(k, 3)

In [7]:
centroids

array([[0.98412915, 0.18576984, 0.15719492],
       [0.10266561, 0.94268002, 0.80225848],
       [0.33269814, 0.02907472, 0.78337485],
       [0.69998682, 0.16548316, 0.63772621],
       [0.54016019, 0.71536075, 0.37835417]])

In [8]:
X[0]

array([0.65315625, 0.40880671, 0.7244756 ])

In [9]:
X[0,:]

array([0.65315625, 0.40880671, 0.7244756 ])

In [10]:
X[0]

array([0.65315625, 0.40880671, 0.7244756 ])

In [11]:
centroids[0]

array([0.98412915, 0.18576984, 0.15719492])

In [12]:
%timeit ((X[0] - centroids[0])**2).sum()

3.51 µs ± 53.1 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [13]:
%timeit np.sum((X[0] - centroids[0])**2)

4.35 µs ± 28.5 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [14]:
%timeit sum((X[0] - centroids[0])**2)

3.03 µs ± 30.3 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [15]:
np.sqrt(((X[0] - centroids[0])**2).sum())

0.6936107515864137

In [16]:
(X[0] - centroids[0])**2

array([0.10954306, 0.04974544, 0.32180737])

In [17]:
def euclidean(x, y):
    return np.sqrt(((x - y)**2).sum())

In [18]:
euclidean(X[0], centroids[0])

0.6936107515864137

In [19]:
np.sqrt(((X[0] - centroids[0])**2).sum())

0.6936107515864137

In [22]:
distances = np.empty((n, k))

for i in range(n):
    for j in range(k):
        distances[i, j] = euclidean(X[i], centroids[j])

In [23]:
distances.argmin(axis = 1)

array([3, 4, 4, ..., 4, 4, 3])

In [24]:
distances

array([[0.69361075, 0.77078585, 0.50035878, 0.26253553, 0.4759659 ],
       [0.71517933, 0.88384092, 1.06600028, 0.75491902, 0.3651727 ],
       [0.50753995, 0.90555402, 0.90037753, 0.59861665, 0.26159413],
       ...,
       [1.00449363, 0.38103088, 0.87479417, 0.76510717, 0.31872383],
       [0.64811005, 0.91696872, 1.00271009, 0.78240118, 0.31971523],
       [0.57135822, 0.87307938, 0.42401879, 0.27425871, 0.47787858]])

In [25]:
np.sqrt(((X[0] - centroids)**2).sum(axis=1))

array([0.69361075, 0.77078585, 0.50035878, 0.26253553, 0.4759659 ])

In [26]:
np.sqrt(((X - centroids[0])**2).sum(axis=1))

array([0.69361075, 0.71517933, 0.50753995, ..., 1.00449363, 0.64811005,
       0.57135822])

In [27]:
X.shape

(10000, 3)

In [28]:
((X.reshape((n, 1, d)) - centroids)**2).sum(axis = 2)

array([[0.48109587, 0.59411083, 0.2503589 , 0.0689249 , 0.22654354],
       [0.51148148, 0.78117477, 1.13635659, 0.56990272, 0.1333511 ],
       [0.25759681, 0.82002808, 0.81067969, 0.3583419 , 0.06843149],
       ...,
       [1.00900745, 0.14518453, 0.76526484, 0.58538899, 0.10158488],
       [0.42004664, 0.84083163, 1.00542753, 0.6121516 , 0.10221783],
       [0.32645022, 0.76226761, 0.17979194, 0.07521784, 0.22836794]])

In [29]:
%timeit distances2 = np.sqrt(((X.reshape((n, 1, d)) - centroids)**2).sum(axis = 2))

1.14 ms ± 2.93 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [ ]:
(distances == distances2).all()

In [ ]:
245 / 1.15

In [30]:
import numba

In [31]:
from numba import jit

In [32]:
def get_distances(X, centroids):
    
    def euclidean(x, y):
        return np.sqrt(((x - y)**2).sum())
    
    distances = np.empty((n, k))

    for i in range(n):
        for j in range(k):
            distances[i, j] = euclidean(X[i], centroids[j])
            
    return distances

In [33]:
%timeit get_distances(X, centroids)

243 ms ± 5.13 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [34]:
get_distances_jit = numba.jit(get_distances, nopython = True)

In [35]:
%timeit get_distances_jit(X, centroids)

2.79 ms ± 17 µs per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [36]:
%%R

x <- c(1, 2, 3)

UsageError: Cell magic `%%R` not found.
