In [1]:
import numpy as np

In [6]:
n = 10000
d = 3
k = 5

In [3]:
X = np.random.rand(n, d)

In [4]:
X.shape

(10000, 3)

In [5]:
X

array([[0.39605896, 0.11604097, 0.01679699],
       [0.48930259, 0.76725228, 0.41477177],
       [0.52120667, 0.67196073, 0.25502133],
       ...,
       [0.05967356, 0.32239034, 0.79961351],
       [0.09248484, 0.52632961, 0.19138143],
       [0.02398592, 0.67596576, 0.35998459]])

In [7]:
centroids = np.random.rand(k, 3)

In [8]:
centroids

array([[0.39676407, 0.97483635, 0.54928742],
       [0.02494271, 0.13572266, 0.71737156],
       [0.57382485, 0.07836188, 0.08784277],
       [0.97685534, 0.31344661, 0.93319702],
       [0.26808593, 0.38518996, 0.26258588]])

In [9]:
X[0]

array([0.39605896, 0.11604097, 0.01679699])

In [10]:
X[0,:]

array([0.39605896, 0.11604097, 0.01679699])

In [11]:
X[0]

array([0.39605896, 0.11604097, 0.01679699])

In [12]:
centroids[0]

array([0.39676407, 0.97483635, 0.54928742])

In [20]:
%timeit ((X[0] - centroids[0])**2).sum()

3.47 µs ± 27.2 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [18]:
%timeit np.sum((X[0] - centroids[0])**2)

4.4 µs ± 71.8 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [23]:
%timeit sum((X[0] - centroids[0])**2)

3.05 µs ± 27.2 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [ ]:
np.sqrt(((X[0] - centroids[0])**2).sum())

In [24]:
(X[0] - centroids[0])**2

array([4.97181551e-07, 7.37529496e-01, 2.83546054e-01])

In [25]:
def euclidean(x, y):
    return np.sqrt(((x - y)**2).sum())

In [26]:
euclidean(X[0], centroids[0])

1.0104830759114138

In [27]:
np.sqrt(((X[0] - centroids[0])**2).sum())

1.0104830759114138

In [40]:
%%timeit

distances = np.empty((n, k))

for i in range(n):
    for j in range(k):
        distances[i, j] = euclidean(X[i], centroids[j])

245 ms ± 15.4 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [37]:
distances.argmin(axis = 1)

array([2, 0, 4, ..., 1, 4, 4])

In [38]:
distances

array([[1.01048308, 0.79304437, 0.19511004, 1.10276128, 0.38630358],
       [0.26410032, 0.84025376, 0.76720047, 0.84404504, 0.46697855],
       [0.44024099, 0.86463687, 0.61893209, 0.89222775, 0.38257653],
       ...,
       [0.77587303, 0.20691736, 0.91132816, 0.92690181, 0.5794637 ],
       [0.64949275, 0.65863597, 0.66564521, 1.17376349, 0.23627572],
       [0.51392873, 0.64775686, 0.85645456, 1.16959513, 0.39194628]])

In [47]:
np.sqrt(((X[0] - centroids)**2).sum(axis=1))

array([1.01048308, 0.79304437, 0.19511004, 1.10276128, 0.38630358])

In [50]:
np.sqrt(((X - centroids[0])**2).sum(axis=1))

array([1.01048308, 0.26410032, 0.44024099, ..., 0.77587303, 0.64949275,
       0.51392873])

In [52]:
X.shape

(10000, 3)

In [59]:
((X.reshape((n, 1, d)) - centroids)**2).sum(axis = 2)

array([[1.02107605, 0.62891937, 0.03806793, 1.21608245, 0.14923046],
       [0.06974898, 0.70602639, 0.58859656, 0.71241203, 0.21806897],
       [0.19381213, 0.74759691, 0.38307693, 0.79607035, 0.1463648 ],
       ...,
       [0.60197896, 0.04281479, 0.83051902, 0.85914697, 0.33577818],
       [0.42184084, 0.43380134, 0.44308355, 1.37772074, 0.05582622],
       [0.26412274, 0.41958895, 0.73351441, 1.36795276, 0.15362188]])

In [67]:
%timeit distances2 = np.sqrt(((X.reshape((n, 1, d)) - centroids)**2).sum(axis = 2))

1.15 ms ± 2.36 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [66]:
(distances == distances2).all()

True

In [68]:
245 / 1.15

213.0434782608696

In [69]:
import numba

In [75]:
from numba import jit

In [70]:
def get_distances(X, centroids):
    
    distances = np.empty((n, k))

    for i in range(n):
        for j in range(k):
            distances[i, j] = euclidean(X[i], centroids[j])
            
    return distances

In [73]:
%timeit get_distances(X, centroids)

237 ms ± 1.01 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [74]:
get_distances_jit = numba.jit(get_distances, nopython = True)

In [76]:
get_distances_jit(X, centroids)

TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Untyped global name 'euclidean': Cannot determine Numba type of <class 'function'>

File "<ipython-input-70-038e67d21f32>", line 6:
def get_distances(X, centroids):
    <source elided>
        for j in range(k):
            distances[i, j] = euclidean(X[i], centroids[j])
            ^
