In [1]:
import rpy2.situation

In [2]:
for row in rpy2.situation.iter_info():
    print(row)

rpy2 version:
3.3.6
Python version:
3.8.6 (tags/v3.8.6:db45529, Sep 23 2020, 15:52:53) [MSC v.1927 64 bit (AMD64)]
Looking for R's HOME:
    Environment variable R_HOME: None
    InstallPath in the registry: C:\Program Files\R\R-4.0.3
    Environment variable R_USER: None
    Environment variable R_LIBS_USER: None
R version:
    In the PATH: None
    Loading R library from rpy2: cannot load library 'C:\Program Files\R\R-4.0.3\bin\x64\R.dll': error 0x7e
Additional directories to load R packages from:
None
C extension compilation:


In [3]:
from rpy2.robjects import pandas2ri

OSError: cannot load library 'C:\Program Files\R\R-4.0.3\bin\x64\R.dll': error 0x7e

In [5]:
import os

In [6]:
#
os.environ['PATH'] = 'C:\\Program Files\\R\\R-4.0.3\\bin\\x64' + os.pathsep + os.environ['PATH']

In [7]:
for row in rpy2.situation.iter_info():
    print(row)

rpy2 version:
3.3.6
Python version:
3.8.6 (tags/v3.8.6:db45529, Sep 23 2020, 15:52:53) [MSC v.1927 64 bit (AMD64)]
Looking for R's HOME:
    Environment variable R_HOME: None
    InstallPath in the registry: C:\Program Files\R\R-4.0.3
    Environment variable R_USER: None
    Environment variable R_LIBS_USER: None
R version:
    In the PATH: 
    Loading R library from rpy2: OK
Additional directories to load R packages from:
None
C extension compilation:


In [16]:
from rpy2.robjects import pandas2ri
from rpy2.robjects.packages import importr
import rpy2.robjects as ro
R = ro.r
pandas2ri.activate()
base = importr('base')

In [17]:
import pandas as pd

In [18]:
weight_df = pd.read_csv("https://raw.githubusercontent.com/mark-andrews/pysc01/master/data/weight.csv")

In [19]:
M = R.lm('weight ~ height', data = weight_df)

In [20]:
R.coef(M)

array([-117.12802067,    1.14813765])

In [21]:
print(base.summary(M))


Call:
(function (formula, data, subset, weights, na.action, method = "qr", 
    model = TRUE, x = FALSE, y = FALSE, qr = TRUE, singular.ok = TRUE, 
    contrasts = NULL, offset, ...) 
{
    ret.x <- x
    ret.y <- y
    cl <- match.call()
    mf <- match.call(expand.dots = FALSE)
    m <- match(c("formula", "data", "subset", "weights", "na.action", 
        "offset"), names(mf), 0L)
    mf <- mf[c(1L, m)]
    mf$drop.unused.levels <- TRUE
    mf[[1L]] <- quote(stats::model.frame)
    mf <- eval(mf, parent.frame())
    if (method == "model.frame") 
        return(mf)
    else if (method != "qr") 
        warning(gettextf("method = '%s' is not supported. Using 'qr'", 
            method), domain = NA)
    mt <- attr(mf, "terms")
    y <- model.response(mf, "numeric")
    w <- as.vector(model.weights(mf))
    if (!is.null(w) && !is.numeric(w)) 
        stop("'weights' must be a numeric vector")
    offset <- model.offset(mf)
    mlm <- is.matrix(y)
    ny <- if (mlm) 
        nrow(y)
   

In [22]:
print(base.summary(M).rx2('coefficients'))

[[-1.17128021e+002  2.87869247e+000 -4.06879241e+001  3.07012392e-320]
 [ 1.14813765e+000  1.67681005e-002  6.84715391e+001  0.00000000e+000]]
